### ISSUE TITLE
Regression: JSON modules no longer loaded between .50 and .51

### ISSUE THREAD

**Issue by dandv** [whitecolor/ts-node-dev#171]
I have a script that imports a JSON file from outside `rootDir` (`import * as packageJson from '../package.json';`) using [this pattern](https://stackoverflow.com/questions/55753163/package-json-is-not-under-rootdir/61426303#61426303) of having `declare module '*.json'; in `../package.json`.

That worked with `ts-node-dev@1.0.0-pre.50`, but fails with `ts-node-dev@1.0.0-pre.51` with the following error:

> error TS2732: Cannot find module '../package.json'. Consider using '--resolveJsonModule' to import module with '.json' extension
> 2 import * as packageJson from '../package.json';

Setting `"resolveJsonModule": true` in `tsconfig.json` is not an option, because `tsc` fails in that case.

**Comment by whitecolor** [comment]
But this test seem to pass https://github.com/whitecolor/ts-node-dev/blob/master/test/index.ts#L143

**Comment by whitecolor** [comment]
Reopen if needed.
